// Core/Tests/ClipKeepCoreTests/PrivacyFilterTests.swift
import XCTest
@testable import ClipKeepCore

final class PrivacyFilterTests: XCTestCase {
    private let filter = PrivacyFilter()

    func test_allowsNormalText() {
        XCTAssertTrue(filter.shouldCapture(types: [PasteboardType.utf8PlainText],
                                           sourceBundleID: "com.apple.TextEdit",
                                           excludedBundleIDs: []))
    }
    func test_rejectsConcealed() {
        XCTAssertFalse(filter.shouldCapture(types: [PasteboardType.utf8PlainText, PasteboardType.concealed],
                                            sourceBundleID: nil, excludedBundleIDs: []))
    }
    func test_rejectsTransientAndAutoGenerated() {
        XCTAssertFalse(filter.shouldCapture(types: [PasteboardType.transient], sourceBundleID: nil, excludedBundleIDs: []))
        XCTAssertFalse(filter.shouldCapture(types: [PasteboardType.autoGenerated], sourceBundleID: nil, excludedBundleIDs: []))
    }
    func test_rejectsExcludedApp() {
        XCTAssertFalse(filter.shouldCapture(types: [PasteboardType.utf8PlainText],
                                            sourceBundleID: "com.agilebits.onepassword7",
                                            excludedBundleIDs: ["com.agilebits.onepassword7"]))
    }
}
