// Core/Sources/ClipKeepCore/Capture/PasteboardReading.swift
import Foundation

/// Abstraction over NSPasteboard so capture logic is testable without AppKit.
public protocol PasteboardReading {
    var changeCount: Int { get }
    func types() -> [String]
    func string(forType type: String) -> String?
    func data(forType type: String) -> Data?
}

public enum PasteboardType {
    public static let utf8PlainText = "public.utf8-plain-text"
    public static let png = "public.png"
    public static let tiff = "public.tiff"
    // nspasteboard.org privacy conventions:
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
}
