// Core/Sources/ClipKeepCore/Capture/PrivacyFilter.swift
import Foundation

public struct PrivacyFilter {
    private let blockedTypes: Set<String> = [
        PasteboardType.concealed, PasteboardType.transient, PasteboardType.autoGenerated,
    ]
    public init() {}

    public func shouldCapture(types: [String], sourceBundleID: String?, excludedBundleIDs: Set<String>) -> Bool {
        if types.contains(where: blockedTypes.contains) { return false }
        if let id = sourceBundleID, excludedBundleIDs.contains(id) { return false }
        return true
    }
}
